# author: gustavo.if.ufrj@gmail.com

# * Problem description:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

flag = T
max = 4e6
fibonacci = c(1, 2)
order = 3
sum = 2

while(flag){
  iter_term = fibonacci[order-1] + fibonacci[order-2]
  if (iter_term <= max){
    fibonacci[order] = iter_term
    if (iter_term %% 2 == 0){
      sum = sum + iter_term
    }
    order = order + 1
  } else {
    flag = F
  }
}

print(sum)
