# Problem: ---------------------------------------------------------------------
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:
#   
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#   
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred
# divisors?

# Solution: --------------------------------------------------------------------

# Find factors function
find_factors = function(num, verbose = T, tol = 1000) {
  factors_length = 0
  for (i in floor(sqrt(num)):1) {
    if ((verbose) & (i%%tol == 0)) print(paste("Testing", i))
    if (num%%i == 0) {
      factors_length = factors_length + 2
      if (verbose) print(paste("Number of factors (so far):", factors_length))
    }
  }
  return(factors_length)
}

# Triangle number function
triangle_num = function(j) {
  return(sum(1:j))
}

# Starting with 7th triangle number
n = 7

t0 = Sys.time()

while(find_factors(triangle_num(n), verbose = F, tol = 1000) <= 500) {
  n = n + 1
}

message('Solver time: ', format(Sys.time() - t0, digits = 2))

print(triangle_num(n))