# Problem: ---------------------------------------------------------------------
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:
#   
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#   
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred
# divisors?

# Solution: --------------------------------------------------------------------

# Find factors function
find_factors = function(num) {
  # Parallelism setup
  library(doParallel)
  library(parallel)
  library(foreach)
  cores = 60
  cl = makeCluster(min(cores, detectCores() - 1), outfile = "")
  registerDoParallel(cl)
  # Usual factors
  default = c(1, num)
  factors = foreach (i = 2:num-1, .combine = "c") %dopar% {
    if (num%%i == 0) {
      return(i)
    }
  }
  factors = c(default, factors)
  factors = factors[order(factors)]
  return(unique(factors))
}

# Starting with 7th triangle number
n = 7; t = sum(1:n)

while(len(find_factors(n)) <= 500) {
  
}